dactilar/urls.py
""" Dactilar id settings """

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path(
        '',
        include(('students.urls', 'students'), namespace='students')
        ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
"""Students url"""
# Django
from django.urls import path

from students import views

urlpatterns = [
    path(
        route='',
        view=views.IndexView.as_view(),
        name='index'),
    path(
        route='busqueda/',
        view=views.SearchStudent.as_view(),
        name='search'),

    path(
        route='registrar/',
        view=views.RegisterStudent.as_view(),
        name='register'),
    path(
        route='total/',
        view=views.ReportStudents.as_view(),
        name='report'),
    path(
        route='reportes/',
        view=views.ReportRationsView.as_view(),
        name='ration-reports'),
    path(
        route='raciones/',
        view=views.FoodRationsView.as_view(),
        name='rations'),
    path(
        route='eliminar-estudiante/<int:pk>/',
        view=views.DeleteStudentView.as_view(),
        name='delete'),
    path(
        route='generate-pdf/',
        view=views.GeneratePDFView.as_view(),
        name='generate-pdf'),
        




    # path(
    #     route='posts/detail/<int:pk>/',
    #     view=views.DetailPostView.as_view(),
    #     name='detail_post'),
]

users/urls.py
"""Users URLs."""

# Django
from django.urls import path
from django.views.generic import TemplateView

# View
from users import views


urlpatterns = [
    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  {% block head_content %}
  {% endblock %}
  {% load static %}
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static "images/logo-fundacion.png" %}" type="image/ico" />

  <title>Fundación Concivica</title>

  <!-- Bootstrap -->
  <link href="{% static 'css/bootstrap.min.css' %}" />
  <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <!-- NProgress -->
  <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
  <!-- iCheck -->
  <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

  <!-- bootstrap-progressbar -->
  <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
  <!-- JQVMap -->
  <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet" />
  <!-- bootstrap-daterangepicker -->
  <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">

  <!-- Custom Theme Style -->
  <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
<link href="{% static 'finger.css' %}" rel="stylesheet">

  {% block css_style %}

  {% endblock css_style %}
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="/" class="site_title"><i class="fa fa-hand-pointer-o"></i> <span>Id. Biométrica</span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <img src="{% static "images/logo-fundacion.png" %}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Bienvenido,</span>
              <h2>{{request.user.get_full_name}}</h2>
            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3>General</h3>
              <ul class="nav side-menu">

                <li><a href="{% url 'students:index' %}"><i class="fa fa-home"></i> Inicio </a>

                </li>
                <li><a href="{% url 'students:register' %}"><i class="fa fa-user"></i> Registrar </a>
                </li>
                <li><a href="{% url 'students:search' %}"><i class="fa fa-search"></i> Búsqueda </a>

                </li>
                
                <li><a href="{% url 'students:report' %}"><i class="fa fa-users"></i> Estudiantes </a>
                </li> 
                
                <li><a><i class="fa fa-cutlery"></i> Raciones Alimenticias<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                  <li><a href="{% url 'students:rations' %}">Resumen</a></li>
                  <!-- <li><a href="{% url 'students:ration-reports' %}">Lista Entregas</a></li> -->
                  <li><a href="{% url 'students:generate-pdf' %}">Reportes PDF</a></li> 
                   

                  </ul>
                  </li>
              </ul>
            </div>

          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">

            <a data-toggle="tooltip" data-placement="top" title="Logout" href="{% url 'users:logout' %}">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                  aria-expanded="false">
                  <img src="{% static "images/logo-fundacion.png" %}" alt="">{{request.user.get_full_name}}
                  <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">

                  <li><a href="{% url 'users:logout' %}"><i class="fa fa-sign-out pull-right"></i>Cerrar sesión</a></li>
                </ul>
              </li>

              <li role="presentation" class="dropdown">
                <!-- <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>{{request.user.get_full_name}}</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul> -->
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->

      <!-- page content -->
      <div class="right_col" role="main">
        {% block content %}

        {% endblock content %}
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
            <strong>© - Powered by:
            <a href="https://github.com/alejandroduquec"> Aduque</a></strong> 
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>

  <!-- jQuery -->
  <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <!-- FastClick -->
  <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
  <!-- NProgress -->
  <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
  <!-- Chart.js -->
  <script src="{% static 'vendors/Chart.js/dist/Chart.min.js' %}"></script>
  <!-- gauge.js -->
  <script src="{% static 'vendors/gauge.js/dist/gauge.min.js' %}"></script>
  <!-- bootstrap-progressbar -->
  <script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
  <!-- iCheck -->
  <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
  <!-- Skycons -->
  <script src="{% static 'vendors/skycons/skycons.js' %}"></script>
  <!-- Flot -->
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script src="{% static 'vendors/Flot/jquery.flot.js' %}"></script>
  <script src="{% static 'vendors/Flot/jquery.flot.pie.js' %}"></script>
  <script src="{% static 'vendors/Flot/jquery.flot.time.js' %}"></script>
  <script src="{% static 'vendors/Flot/jquery.flot.stack.js' %}"></script>
  <script src="{% static 'vendors/Flot/jquery.flot.resize.js' %}"></script>
  <!-- Flot plugins -->
  <script src="{% static 'vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
  <script src="{% static 'vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
  <script src="{% static 'vendors/flot.curvedlines/curvedLines.js' %}"></script>
  <!-- DateJS -->
  <script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
  <!-- JQVMap -->
  <script src="{% static 'vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
  <script src="{% static 'vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
  <script src="{% static 'vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
  <!-- bootstrap-daterangepicker -->
  <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
  <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

  <!-- Custom Theme Scripts -->
  <script src="{% static 'build/js/custom.min.js' %}"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
 


 

  {% block js_scripts %}
    
  {% endblock js_scripts %}
  {% load sweetify %}
  {% sweetify %}
</body>

</html>