dactilar/urls.py
""" Dactilar id settings """

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path(
        '',
        include(('students.urls', 'students'), namespace='students')
        ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Users URLs."""

# Django
from django.urls import path
from django.views.generic import TemplateView

# View
from users import views


urlpatterns = [
    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
]

users/models.py
"""users model"""

from django.db import models
from django.contrib.auth.models import User

ROL_CHOICES = (
    (1, 'Admin'),
    (2, 'Consulta')
)


class Institution(models.Model):
    """Institutions model"""
    name = models.CharField('Nombre', max_length=30)

    def __str__(self):
        """return name"""
        return self.name


class Profile(models.Model):
    """Profile model that extens the db with other informations"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.PositiveIntegerField(
        'Rol',
        choices=ROL_CHOICES,
    )
    institution = models.OneToOneField(
        Institution,
        on_delete=models.CASCADE,
        blank=True,
        null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """return username"""
        return self.user.username

users/views.py
""" Users view"""

# Django
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.shortcuts import render, redirect
from django.views.generic import DetailView, FormView, UpdateView
from django.urls import reverse_lazy

# Models
from django.contrib.auth.models import User
from users.models import Profile


class LoginView(auth_views.LoginView):
    """Login view"""
    template_name = 'users/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """logout view"""
    template_name = 'users/login.html'

templates/users/delete_user.html
{% extends "base/base.html" %}
{% load staticfiles %}
{% block content %}
<!-- page content -->

    <div class="">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="page-title">
                <div class="title_left">
                    <h3>Confirmación<small></small></h3>
                </div>
            </div>
            <div class="x_panel">
                <div class="x_content">
                    <form role="form" method="post">

                        {% csrf_token %}

                        <h3>¿Desea eliminar {{object}} ? </h3>

                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-danger" id="load"
                                        data-loading-text="<i class='fa fa-circle-o-notch fa-spin'></i> Procesando">Sí,
                                        eliminar</button>
                                    <a onclick="goBack()" class="btn btn-default">
                                        Cancelar
                                    </a>
                                </div>
                            </div>
                            <!-- /.col-lg-6 (nested) -->
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock  %}

{% block js_scripts %}
<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock %}

templates/users/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% load static %}
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static "images/logo-fundacion.png" %}" type="image/ico" />

    <title>Fundación Concivica</title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static 'vendors/animate.css/animate.min.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
</head>

<body class="login">
    <div>
        <a class="hiddenanchor" id="signup"></a>
        <a class="hiddenanchor" id="signin"></a>

        <div class="login_wrapper">
            <div class="animate form login_form">
                <section class="login_content">
                    <form method="POST" action="{% url 'users:login'%}">
                        {% csrf_token %}
                        <h1> Fundación Concivica </h1>
                        <div>
                            <input class="form-control" type="text" name="username" placeholder="Nombre de usuario"
                                required="true">
                        </div>
                        <div>
                            <input class="form-control" type="password" name="password" placeholder="Contraseña"
                                required="true">
                        </div>
                        {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible fade in" role="alert" style="text-shadow:none">
                                
                                <strong> Error !</strong> Nombre de usuario o contraseña incorrectos.
                              </div>
                        {% endif %}
                        <div>
                            <button class="btn btn-default" type="submit">Iniciar Sesión</button>

                        </div>

                        <div class="clearfix"></div>

                        <div class="separator">
                            <p class="change_link">Municipio de Rionegro

                            </p>

                            <div class="clearfix"></div>
                            <br />

                            <div>
                                <h1><i class="fa fa-hand-pointer-o"></i> Identificación Biométrica</h1>
                                <p>©2019 Todos los derechos reservados.</p>
                                <p></p>
                            </div>
                        </div>
                    </form>
                </section>
            </div>


        </div>
    </div>
</body>

</html>